name: personal_finance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  phosphor_flutter: ^2.1.0
  riverpod_annotation: ^3.0.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
